charmap " ",$0
charmap "!",$1
charmap "\"",$2
charmap "#",$3
charmap "$",$4
charmap "%",$5
charmap "&",$6
charmap "'",$7
charmap "(",$8
charmap ")",$9
charmap "*",$A
charmap "+",$B
charmap ",",$C
charmap "-",$D
charmap ".",$E
charmap "/",$F
charmap "0",$10
charmap "1",$11
charmap "2",$12
charmap "3",$13
charmap "4",$14
charmap "5",$15
charmap "6",$16
charmap "7",$17
charmap "8",$18
charmap "9",$19
charmap ":",$1A
charmap ";",$1B
charmap "<",$1C
charmap "=",$1D
charmap ">",$1E
charmap "?",$1F
charmap "@",$20
charmap "A",$21
charmap "B",$22
charmap "C",$23
charmap "D",$24
charmap "E",$25
charmap "F",$26
charmap "G",$27
charmap "H",$28
charmap "I",$29
charmap "J",$2A
charmap "K",$2B
charmap "L",$2C
charmap "M",$2D
charmap "N",$2E
charmap "O",$2F
charmap "P",$30
charmap "Q",$31
charmap "R",$32
charmap "S",$33
charmap "T",$34
charmap "U",$35
charmap "V",$36
charmap "W",$37
charmap "X",$38
charmap "Y",$39
charmap "Z",$3A
charmap "[",$3B
charmap "\\",$3C
charmap "]",$3D
charmap "^",$3E
charmap "_",$3F
charmap "`",$40
charmap "a",$41
charmap "b",$42
charmap "c",$43
charmap "d",$44
charmap "e",$45
charmap "f",$46
charmap "g",$47
charmap "h",$48
charmap "i",$49
charmap "j",$4A
charmap "k",$4B
charmap "l",$4C
charmap "m",$4D
charmap "n",$4E
charmap "o",$4F
charmap "p",$50
charmap "q",$51
charmap "r",$52
charmap "s",$53
charmap "t",$54
charmap "u",$55
charmap "v",$56
charmap "w",$57
charmap "x",$58
charmap "y",$59
charmap "z",$5A
charmap "\{",$5B
charmap "|",$5C
charmap "\}",$5D
charmap "~",$5E
